language:
    - php

php:
    - hhvm
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer install

script:
    - composer test
    - composer check-style

after_script:
    - php vendor/bin/coveralls -v
